spring:
  application:
    name: spaceship
  datasource:
    url: jdbc:h2:mem:spaceship_db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
