spring:
  application:
    name: spaceship
  datasource:
    url: jdbc:h2:mem:spaceship_db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m

logging:
  level:
    '[com.project]': warn
